// Copyright © 2026 Racpast. All Rights Reserved.
//
// This file is part of SNIBypassGUI, a proprietary software project.
//
// NOTICE: All information contained herein is, and remains the property of
// Racpast. The intellectual and technical concepts contained herein are
// proprietary to Racpast and are protected by copyright law and international
// treaties. Dissemination of this information or reproduction of this material
// is strictly forbidden unless prior written permission is obtained from Racpast.
//
// Unauthorized copying, modification, distribution, or use of this file,
// via any medium, is strictly prohibited.
//
// For licensing inquiries: snibypassgui@gmail.com or racpast@gmail.com
//
// See the LICENSE.md file in the project root for full terms and conditions.

// Auto-generated by tools/release.py — do not edit.
// ECDSA P-256 public key (uncompressed point X||Y, 64 bytes) used to
// verify update manifests. The matching private key never leaves the
// release machine / CI secret store.
#pragma once
static const unsigned char kUpdatePublicKey[64] = {
    0x32, 0x8f, 0xb6, 0x3f, 0x30, 0x54, 0x5b, 0xb9, 0x3a, 0x11, 0x78, 0x00, 0xa4, 0xaf, 0xf1, 0x68, 0xe5, 0x24, 0x8f, 0xdc, 0x21, 0xba, 0xf0, 0xbd, 0xd5, 0xbe, 0xdc, 0x41, 0x16, 0xb9, 0xb3, 0x52, 0x59, 0x48, 0x96, 0x39, 0xe0, 0x28, 0xe2, 0x03, 0x8a, 0xb2, 0x95, 0x9a, 0x1e, 0x97, 0x3a, 0xc4, 0x24, 0x93, 0xce, 0x9e, 0x8a, 0x91, 0xa7, 0x19, 0x4a, 0xba, 0xce, 0x2b, 0xe7, 0x9f, 0x16, 0xe7
};
